site_name: Modern C++
site_url: https://alandefreitas.github.io/moderncpp/
repo_url: https://github.com/alandefreitas/moderncpp
repo_name: alandefreitas/moderncpp

site_description: Modern C++ Snippets

theme:
  name: material
  palette:
    scheme: preference
  features:
    - navigation.instant # this doesn't work well with pymdownx.arithmatex
    # - navigation.sections
    - toc.integrate
    # - header.autohide # this has caused problems for some mobile devices
  icon:
    repo: fontawesome/brands/git-alt

edit_uri: ""

plugins:
  - search
  - awesome-pages

google_analytics:
  - UA-109858331-3
  - auto

copyright: Copyright &copy; 2020 Alan Freitas

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - meta

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js